version: '3.8'
services:
  db:
    container_name: dio_workspace
    image:  mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE = db_workshop
      - MYSQL_USER = root
      - MYSQL_PASSWORD = root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    expose:
      - '3306'